### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by satrik** [satrik/homebridge-bslamp2#5]
Since the last update my lamps won't respond sometimes. I think the issue appears only after a restart of my raspberry pi and only a restart of the (child) bridge helps to fix this issue. 

Need to investigate what fails and why there is no error log.

**Comment by satrik** [comment]
I think the problem is within the persistent connection of the hap-controller, but I still don't know why there are no errors. 

At least it works if I call `client.close()` after a few seconds without user input. This way the same connection would be used for all changed characteristics (brightness, saturation, hue, power) and will be closed afterwards. But this way also means the first action after the connection is closed, could delay as long as the verify process needs (~ 1 sec). 

Will make some tests to find a nice working solution

**Comment by JohnG1985** [comment]
It's difficult to say exactly what the issue might be without more information. It's possible that the problem is related to the persistent connection of the hap-controller, but it's also possible that there is an issue with the raspberry pi itself or some other component in your setup.

One thing you could try is to enable debugging in your hap-controller to see if that provides any additional information about the problem. You can do this by setting the debug option to true in your hap-controller configuration.

Additionally, you may want to check the logs on your raspberry pi to see if there are any relevant error messages there. This could help you identify the source of the problem and determine the best way to fix it.

Another thing you could try is implementing a retry mechanism in your code. If the hap-controller is unable to establish a connection, your code could try to reconnect a few times before giving up. This could help to prevent issues related to temporary connectivity problems.

Overall, it's important to do thorough testing and debugging to identify the root cause of the problem. Once you have a better understanding of the issue, you'll be better equipped to find a solution.

**Comment by satrik** [comment]
1.0.4 should fix the problems
